# Generated by Django 2.1.5 on 2022-10-24 17:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.CharField(max_length=3)),
                ('card_2', models.CharField(max_length=3)),
                ('card_3', models.CharField(max_length=3)),
                ('card_4', models.CharField(max_length=3)),
                ('card_5', models.CharField(max_length=3)),
                ('current_player', models.IntegerField(default=0)),
                ('raise_amount', models.IntegerField(default=0)),
                ('current_bet', models.IntegerField(default=0)),
                ('player_pot', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('check_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('seat_num', models.IntegerField(default=0)),
                ('card_1', models.CharField(default='', max_length=3)),
                ('card_2', models.CharField(default='', max_length=3)),
                ('player_pot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no_of_players', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('blinds', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=False)),
                ('dealer', models.IntegerField(default=-1)),
                ('big_blind', models.IntegerField(default=1)),
                ('small_blind', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='poker.Table'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hand',
            name='players',
            field=models.ManyToManyField(to='poker.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_hand', to='poker.Table'),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner',
            field=models.ManyToManyField(related_name='winning_hands', to='poker.Player'),
        ),
    ]
