# Generated by Django 2.0.8 on 2018-11-29 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.CharField(max_length=500)),
                ('card_2', models.CharField(max_length=500)),
                ('card_3', models.CharField(max_length=500)),
                ('card_4', models.CharField(max_length=500)),
                ('card_5', models.CharField(max_length=500)),
                ('pot', models.IntegerField(default=0)),
                ('preflop_betting', models.IntegerField(default=0)),
                ('flop_betting', models.IntegerField(default=0)),
                ('turn_betting', models.IntegerField(default=0)),
                ('river_betting', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField(default=1000)),
                ('card_1', models.CharField(default='', max_length=500)),
                ('card_2', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blinds', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poker.Table'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hand',
            name='current_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='current_user', to='poker.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='players',
            field=models.ManyToManyField(to='poker.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_hand', to='poker.Table'),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner',
            field=models.ManyToManyField(related_name='winning_hands', to='poker.Player'),
        ),
    ]
