# Generated by Django 2.0.8 on 2018-11-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='flop_betting',
            new_name='sub_pot',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='preflop_betting',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='river_betting',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='turn_betting',
        ),
    ]
