# Generated by Django 2.0.8 on 2018-11-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='current_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_user', to='poker.Player'),
        ),
    ]
