# Generated by Django 2.0.8 on 2018-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20181129_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='starting_chips',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.IntegerField(default=0),
        ),
    ]
