# Generated by Django 2.0.8 on 2018-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_auto_20181129_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='starting_chips',
        ),
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.IntegerField(default=1000),
        ),
    ]
