# Generated by Django 2.0.8 on 2018-11-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_auto_20181129_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='current_player',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='poker.Table'),
        ),
    ]
