# Generated by Django 2.0.8 on 2018-11-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_auto_20181129_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seat_num',
            field=models.IntegerField(default=0),
        ),
    ]
