# Generated by Django 2.0.8 on 2018-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_player_seat_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='player_bet',
            field=models.IntegerField(default=0),
        ),
    ]
