# Generated by Django 2.0.8 on 2018-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_hand_check_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='no_of_players',
            field=models.IntegerField(default=0),
        ),
    ]
