# Generated by Django 2.0.8 on 2018-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_table_no_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='no_of_active_players',
            field=models.IntegerField(default=0),
        ),
    ]
