# Generated by Django 2.0.8 on 2018-12-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0010_hand_no_of_active_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='player_bet',
            new_name='current_bet',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='sub_pot',
            new_name='raise_amount',
        ),
    ]
