# Generated by Django 2.0.8 on 2018-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0011_auto_20181206_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_pot',
            field=models.IntegerField(default=0),
        ),
    ]
