# Generated by Django 2.0.8 on 2018-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0012_player_player_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='player_pot',
            field=models.IntegerField(default=0),
        ),
    ]
