# Generated by Django 2.0.8 on 2018-12-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0013_hand_player_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
