# Generated by Django 2.0.8 on 2018-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0014_table_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
