# Generated by Django 2.0.8 on 2019-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0015_auto_20181214_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='no_of_active_players',
        ),
        migrations.AddField(
            model_name='hand',
            name='dealer',
            field=models.IntegerField(default=0),
        ),
    ]
