# Generated by Django 2.0.8 on 2019-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0016_auto_20190108_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='dealer',
        ),
        migrations.AddField(
            model_name='table',
            name='dealer',
            field=models.IntegerField(default=-1),
        ),
    ]
