# Generated by Django 2.0.8 on 2019-01-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0017_auto_20190109_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='big_blind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='small_blind',
            field=models.IntegerField(default=0),
        ),
    ]
