# Generated by Django 2.0.8 on 2019-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0018_auto_20190109_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='big_blind',
            field=models.IntegerField(default=1),
        ),
    ]
