# Generated by Django 2.0.8 on 2019-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0019_auto_20190109_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='check_no',
            field=models.IntegerField(default=1),
        ),
    ]
