# Generated by Django 2.0.8 on 2019-01-09 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0020_auto_20190109_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='no_of_players',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
