# Generated by Django 2.0.8 on 2019-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0021_auto_20190109_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
